### ISSUE TITLE
Undefined index and invalid number of prepared parameters

### ISSUE THREAD

**Issue by NotionCommotion** [doctrine/orm#7707]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 1.6.1

#### Summary

When creating a new bi-directional one-to-one record, Doctrine complains about undefined index and then throws a PDO exception.

#### Current behavior

As seen by the MariaDB log, the first three queries execute, but the last one (client_datalog) fails as Doctrine doesn't include the parent's PK to be used as this table's PK.

#### How to reproduce

Execute the following script:

```
<?php
//create.php
error_reporting(E_ALL);
ini_set('display_startup_errors', 1);
ini_set('display_errors', 1);
ini_set("log_errors", 1);

require_once "bootstrap.php";

$point = new RealPoint();
$point->setName('PointName');
$point->setSomeProperty('SomePointProperty');
$datanode=new ClientDatanode();
$datanode->setName('DatanodeName');
$datanode->setSomeProperty('SomeDatanodeProperty');
$datanode->setPoint($point);

$entityManager->persist($point);
$entityManager->flush();
```

```
[michael@devserver testing]$ php create.php

Notice: Undefined index: 000000006cf4ecfa000000001f9eb34a in /var/www/testing/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2995

Fatal error: Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in /var/www/testing/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
Stack trace:
#0 /var/www/testing/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute(NULL)
#1 /var/www/testing/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(153): Doctrine\DBAL\Driver\PDOStatement->execute(NULL)
#2 /var/www/testing/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php(213): Doctrine\DBAL\Statement->execute()
#3 /var/www/testing/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1073): Doctrine\ORM\Persisters\Entity\JoinedSubclassPersister->executeInserts()
#4 /var/www/testing/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(386): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /var/www/testing/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(359): Do in /var/www/testing/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 106
[michael@devserver testing]$

```

```
190513 18:32:15     69 Connect  michael@localhost as anonymous on doctrinetest
                    69 Query    START TRANSACTION
                    69 Query    INSERT INTO point (name, type) VALUES ('PointName', 'RealPoint')
                    69 Query    INSERT INTO real_point (id, someProperty) VALUES (8, 'SomePointProperty')
                    69 Query    INSERT INTO datanode (name, id, type) VALUES ('DatanodeName', 8, 'ClientDatanode')
                    69 Query    ROLLBACK
                    69 Quit
```

```
<?php
use Doctrine\ORM\Mapping as ORM;

/**
 * Point
 *
 * @Table(name="point")
 * @InheritanceType("JOINED")
 * @DiscriminatorColumn(name="type", type="string", length=32)
 * @DiscriminatorMap({"RealPoint" = "RealPoint", "VirtualPoint" = "VirtualPoint"})
 * @Entity
 */
abstract class Point
{
    /**
     * @var int
     *
     * @Column(name="id", type="integer")
     * @Id
     * @GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /** @Column(type="string") */
    private $name;


    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    public function getName()
    {
        return $this->name;
    }
    public function setName($name)
    {
        $this->name = $name;
    }
}
```

```
<?php
use Doctrine\ORM\Mapping as ORM;

/**
 * RealPoint
 *
 * @Table(name="real_point")
 * @Entity
 */
class RealPoint extends Point
{
    /**
     * @var \Datanode
     *
     * @OneToOne(targetEntity="Datanode", mappedBy="point", cascade={"persist","remove"}, orphanRemoval=true)
     */
    private $datanode;

    /** @Column(type="string") */
    private $someProperty;


    /**
     * Set datanode.
     *
     * @param \Datanode|null $datanode
     *
     * @return RealPoint
     */
    public function setDatanode(\Datanode $datanode = null)
    {
        $this->datanode = $datanode;

        return $this;
    }

    /**
     * Get datanode.
     *
     * @return \Datanode|null
     */
    public function getDatanode()
    {
        return $this->datanode;
    }

    public function getSomeProperty()
    {
        return $this->someProperty;
    }
    public function setSomeProperty($someProperty)
    {
        $this->someProperty = $someProperty;
    }
}

```

```
<?php
use Doctrine\ORM\Mapping as ORM;

/**
 * Datanode
 *
 * @Table(name="datanode")
 * @InheritanceType("JOINED")
 * @DiscriminatorColumn(name="type", type="string", length=32)
 * @DiscriminatorMap({"ServerDatanode" = "ServerDatanode", "ClientDatanode" = "ClientDatanode"})
 * @Entity
 */
abstract class Datanode
{
    /**
     * @var \RealPoint
     *
     * @Id
     * @GeneratedValue(strategy="NONE")
     * @OneToOne(targetEntity="RealPoint", inversedBy="datanode")
     * @JoinColumns({
     *   @JoinColumn(name="id", referencedColumnName="id", onDelete="CASCADE")
     * })
     */
    private $point;

    /** @Column(type="string") */
    private $name;


    /**
     * Set point.
     *
     * @param \RealPoint $point
     *
     * @return Datanode
     */
    public function setPoint(\RealPoint $point)
    {
        $point->setDatanode($this);
        $this->point = $point;

        return $this;
    }

    /**
     * Get point.
     *
     * @return \RealPoint
     */
    public function getPoint()
    {
        return $this->point;
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    public function getName()
    {
        return $this->name;
    }
    public function setName($name)
    {
        $this->name = $name;
    }
}

```

```
<?php
use Doctrine\ORM\Mapping as ORM;

/**
 * ClientDatanode
 *
 * @Table(name="client_datanode")
 * @Entity
 */
class ClientDatanode extends Datanode
{

    /** @Column(type="string") */
    private $someProperty;

    public function getSomeProperty()
    {
        return $this->someProperty;
    }
    public function setSomeProperty($someProperty)
    {
        $this->someProperty = $someProperty;
    }
}
```

#### Expected behavior

No error.

**Comment by SenseException** [comment]
Thank you for reporting this issue. Can you please create a PR containing a failing test for this? I assume this should be able with `UnitOfWork::getEntityIdentifier()`.

**Comment by NotionCommotion** [comment]
Hi SenseException.  Not really sure about PR, but just uploaded the scripts to https://github.com/NotionCommotion/doctrine_github_issue_7707.  In the root directory, just type "php create.php", and you will see the error.  Thanks
