### ISSUE TITLE
Call to a member function getSqlExecutor() on null with DQL of "0"

### ISSUE THREAD

**Issue by ntzm** [doctrine/orm#7982]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.7.0

#### Summary

When executing a DQL query of "0", it throws a PHP fatal error

#### Current behavior

```
Fatal error: Uncaught Error: Call to a member function getSqlExecutor() on null in /home/nat/Code/personal/fuzzer-test/doctrine-dql/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php:298
Stack trace:
#0 /home/nat/Code/personal/fuzzer-test/doctrine-dql/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(992): Doctrine\ORM\Query->_doExecute()
#1 /home/nat/Code/personal/fuzzer-test/doctrine-dql/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(947): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, NULL)
#2 /home/nat/Code/personal/fuzzer-test/doctrine-dql/test.php(12): Doctrine\ORM\AbstractQuery->execute()
#3 {main}
  thrown in /home/nat/Code/personal/fuzzer-test/doctrine-dql/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php on line 298
```

#### How to reproduce

```
<?php

require __DIR__ . '/vendor/autoload.php';

$config = \Doctrine\ORM\Tools\Setup::createAnnotationMetadataConfiguration(['/empty'], true);
$em = \Doctrine\ORM\EntityManager::create([
    'driver' => 'pdo_sqlite',
], $config);

$em->createQuery('0')->execute();
```

#### Expected behavior

Parse error

**Comment by beberlei** [comment]
This is fixed in #7987
